Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2019-08, with the labels that each got.

#26 [JENKINS-58919] Fix date time parsing for MR webhook
  pom.xml
Labels: Do Not Merge

#32 Travis should only build master and PRs
  .travis.yml
Labels: chore

#33 release drafter ooopsie :man_facepalming:
  .github/release-drafter.yml
Labels: skip-changelog

#35 Add GitLab Commit link
  .editorconfig
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMBuilder.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabBrowser.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabHelper.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabIcons.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabLink.java
Labels: enhancement

#36 add web hook cause
  src/main/java/io/jenkins/plugins/gitlabbranchsource/AbstractGitLabSCMHeadEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestSCMEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabPushSCMEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMCauseAction.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabTagPushSCMEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabWebHookCause.java
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/Messages.properties
Labels: enhancement
