Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2019-09, with the labels that each got.

#44 Add i10n support
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/TriggerMRCommentTrait/config.jelly
Labels: enhancement

#42 Fix the IndexOutOfBoundsException because of no GitLabServers check
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
Labels: bugfix

#46 only call getHookUrl if credential is not null
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
Labels: bugfix

#47 fix deprecated API calls
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMBuilder.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/SSHCheckoutTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
Labels: chore

#49 Fix IndexOutOfBounds on push of new branch
  src/main/java/io/jenkins/plugins/gitlabbranchsource/AbstractGitLabSCMHeadEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabPushSCMEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabTagPushSCMEvent.java
Labels: bugfix

#51 Fix badge and fix installation instructions
  README.md
Labels: documentation

#52 use spotbugs annotations and add missing declaration of annotation on overrides
  src/main/java/io/jenkins/plugins/gitlabbranchsource/AbstractGitLabSCMHeadEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/BranchDiscoveryTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/ForkMergeRequestDiscoveryTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabProjectSCMEvent.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMFile.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/HookRegistrationTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/LogCommentTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/MergeWithGitSCMExtension.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/OriginMergeRequestDiscoveryTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/SkipNotificationsTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/TagDiscoveryTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/TriggerMRCommentTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabBrowser.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabLink.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
  src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServers.java
Labels: chore

#45 [JENKINS-59184] Add gitlab avatar cache
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabAvatar.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabAvatarCache.java
Labels: enhancement

#48 Impl GitLabAvatarTrait
  README.md
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabAvatarTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSourceContext.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/LogCommentTrait.java
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/GitLabAvatarTrait/config.jelly
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/GitLabAvatarTrait/help-disableProjectAvatar.html
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/Messages.properties
Labels: bugfix

#50 Initialize transient fields after XStream deserialization
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/test/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSourceDeserializationTest.java
Labels: bugfix

#54 fix potential null pointer in lightweight checkout and support fetching Jenkinsfile from directory
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMFile.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMFileSystem.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
Labels: enhancement
