Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2020-04, with the labels that each got.

#80 [JENKINS-61320, JENKINS-59753] Remove transient modifier for ssh and http remote in scmsource
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
Labels: bugfix

#82 update developer name 😅
  pom.xml
Labels: skip-changelog

#81 [JENKINS-61760] Use git plugin's MergeWithSCMExtension Class
  pom.xml
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMBuilder.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/MergeWithGitSCMExtension.java
Labels: enhancement

#76 fix(MergeRequestCommentTrigger): job scan premature exit
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java
Labels: bugfix

#83 Fetch project id in SCMSource constructor
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource/config-detail.jelly
Labels: bugfix

#84 enable configuration of an alternative Jenkins root URL for hooks
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabHelper.java
  src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java
  src/main/resources/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer/config.groovy
  src/main/resources/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer/help-hooksRootUrl.html
  src/test/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreatorParameterizedTest.java
  src/test/java/io/jenkins/plugins/gitlabserverconfig/casc/ConfigurationAsCodeTest.java
  src/test/resources/io/jenkins/plugins/gitlabserverconfig/casc/configuration-as-code.yml
  src/test/resources/io/jenkins/plugins/gitlabserverconfig/casc/expected_output.yml
Labels: enhancement

#75 [JENKINS-61020] Add configurable commit status identifier
  src/main/java/io/jenkins/plugins/gitlabbranchsource/BuildStatusNameCustomPartTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSourceContext.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/BuildStatusNameCustomPartTrait/config.jelly
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/BuildStatusNameCustomPartTrait/help-buildStatusContextPrefix.html
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/Messages.properties
Labels: enhancement

#88 [JENKINS-60304] Forward GitLabApiException as IOException
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMFileSystem.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
Labels: bugfix

#86 [JENKINS-61683] Initial implementation of GitLab Hook parameters as env variable
  .gitignore
  README.md
  docs/img/add-server.png
  docs/img/branch-build-strategy.gif
  docs/img/branch-source.png
  docs/img/server-config.png
  pom.xml
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabCauseUtils.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabMergeRequestCauseData.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabPushCauseData.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabTagPushCauseData.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Environment/GitLabWebHookEnvironmentContributor.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabWebHookCause.java
Labels: documentation, enhancement
