Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2022-04, with the labels that each got.

#190 enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore

#192 Remove Travis
  .travis.yml
  README.md
Labels: chore

#181 [JENKINS-63102] Added two new Project Naming Strategies for "Contextual Project Path" and "Simple Project Path"
  README.md
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/ProjectNamingStrategyTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
  src/main/resources/index.jelly
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/Messages.properties
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/ProjectNamingStrategyTrait/help-strategyId.html
Labels: enhancement

#194 Bump plugin BOM from 1280.vd669827e38cd to 1289.v5c4b_1c43511b_
  pom.xml
Labels: dependencies

#156 Allow users without global Job/Build permission configure multibranch jobs
  .gitignore
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMFileSystem.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabHelper.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
  src/main/java/io/jenkins/plugins/gitlabserverconfig/action/GitlabAction.java
  src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java
Labels: enhancement
