Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2023-06, with the labels that each got.

#324 Fix case where "SecretTokenAsPlainText" is null
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSystemHookAction.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabWebHookAction.java
Labels: bug

#330 Fix link to GitLab when server ends with a slash
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabHelper.java
  src/test/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabHelperTest.java
Labels: bug

#331 Update hamcrest
  pom.xml
Labels: dependencies

#307 Option to ignore type in build StatusName
  src/main/java/io/jenkins/plugins/gitlabbranchsource/BuildStatusNameCustomPartTrait.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSourceContext.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java
  src/main/resources/io/jenkins/plugins/gitlabbranchsource/BuildStatusNameCustomPartTrait/config.jelly
  src/test/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifierTest.java
Labels: enhancement
