Repository jenkinsci/gitlab-branch-source-plugin, pull requests merged in 2024-01, with the labels that each got.

#381 Fix wrong links to GitLab when server is behind a proxy
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java
  src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java
Labels: bug

#389 doc: fix creating GitLab Group
  README.md
Labels: documentation

#387 Adding GITLAB_USER_USERNAME variable to GitLabPushCauseData and GitLabTagPushCauseData
  README.md
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabPushCauseData.java
  src/main/java/io/jenkins/plugins/gitlabbranchsource/Cause/GitLabTagPushCauseData.java
Labels: enhancement

#386 Forward compatibility with Guice 7
  pom.xml
  src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
Labels: internal
